[workspace]
channels  = ['conda-forge']
name      = "reactive-context-toolkit"
platforms = ['win-64', 'linux-64']

[target.unix.activation]
scripts = ["scripts/install.sh"]

[target.win.activation]
scripts = ["scripts/install.bat"]
