export { loadConfig } from './loader'
export { validateConfig, desugarFileInjections } from './schema'
export { buildFileRegistry } from './files'
export { deriveFromProject } from './derive'
export type { DerivedConfig } from './derive'
export type * from './types'
